stages:
  - test


test:
  image: python:3.7
  stage: test
  before_script:
  - apt-get update
  - apt-get install -y gconf-service libasound2 libatk1.0-0 libcairo2 libcups2 libfontconfig1 libgdk-pixbuf2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libxss1 fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils libappindicator3-1
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install

  script:
  - apt-get -y install python3-pip
  - pip3 install -r requirements.txt
  - pytest